Repository ladybug-tools/lbt-grasshopper, pull requests merged in 2020-07, with the labels that each got.

#100 docs(installer): Update installer to latest version
  installer.gh
Labels: enhancement

#103 fix(deps): Add ruby-requirements.txt file + track OpenStudio gem version
  README.md
  ruby-requirements.txt
Labels: enhancement

#111 feat(installer): Release new installer with versioner component
  installer.gh
Labels: enhancement

#124 docs(installer): Update installer to manage existing honeybee[+]
  installer.gh
Labels: enhancement

#123 ci(actions): bump honeybee-openstudio-gem on repository dispatch event
  .github/workflows/dependency-release.yaml
Labels: enhancement

#134 docs(installer): Updated installer to latest ladybug_rhino fix
  installer.gh
Labels: bug

#141 fix(installer): Trigger new release with installer update
  installer.gh
  ruby-requirements.txt
Labels: enhancement

#144 fix(deps): bump honeybee-grasshopper-energy from 1.8.4 to 1.8.5
  requirements.txt
Labels: dependencies
